name:                ply
version:             0.1.0
github:              "amcknight/ply"
license:             BSD3
author:              "Andrew McKnight"
maintainer:          "thedonk@gmail.com"
copyright:           "2019-2020 Andrew McKnight"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/amcknight/ply#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- cassava
- vector
- split
- containers
- ordered-containers
- text
- megaparsec
- parser-combinators
- filepath

library:
  source-dirs: src

executables:
  ply:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ply

tests:
  ply-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ply
    - utf8-string
    - tasty
    - tasty-hunit
    - tasty-golden
