name:                csvsql
version:             0.0.3
github:              "amcknight/csvsql"
license:             BSD3
author:              "Andrew McKnight"
maintainer:          "thedonk@gmail.com"
copyright:           "2019-2020 Andrew McKnight"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis: Run SQL queries on raw CSVs
# category: ?

description:         Please see the README on GitHub at <https://github.com/amcknight/csvsql#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- cassava
- vector
- split
- ordered-containers
- text
- megaparsec
- parser-combinators

library:
  source-dirs: src

executables:
  csvsql:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - csvsql

tests:
  csvsql-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - csvsql
    - utf8-string
    - tasty
    - tasty-hunit
